/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.categoriaController;
import controller.produtoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Categoria;
import model.bean.Produto;

/**
 *
 * @author filip
 */
public class produtoView extends javax.swing.JFrame {

    produtoController produtoController = new produtoController();
    
    public produtoView() {
        initComponents();
        DefaultTableModel modeloProdutos = (DefaultTableModel) jTable_produtos.getModel();
        this.setDefaultCloseOperation(produtoView.HIDE_ON_CLOSE);
    }
    
    public void getListaProdutos(){
        DefaultTableModel modeloProdutos = (DefaultTableModel) jTable_produtos.getModel();
        modeloProdutos.setRowCount(0);
        
        for(Produto p : produtoController.read()){
            
            modeloProdutos.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getValor(),
                p.getCategoria().getDescricao()
            });
        }
    }
    
    public void limparCampos(){
        jTextField_descricao.setText("");
        jTextField_qtd.setText("");
        jTextField_valor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_qtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton_add = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_produtos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadio_descri = new javax.swing.JRadioButton();
        jRadio_categoria = new javax.swing.JRadioButton();
        jTextField_busca = new javax.swing.JTextField();
        jButton_busca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Quantidade:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Categoria:");

        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_add.setText("Adicionar");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_update.setText("Atualizar");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_delete.setText("Remover");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTable_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Quantidade", "Valor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_produtos);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Buscar por:");

        buttonGroup1.add(jRadio_descri);
        jRadio_descri.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadio_descri.setText("Descrição");
        jRadio_descri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_descriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_categoria);
        jRadio_categoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadio_categoria.setText("Categoria");

        jButton_busca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Start-Menu-Search-icon.png"))); // NOI18N
        jButton_busca.setText("Busca");
        jButton_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addComponent(jButton_add)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_update)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(jTextField_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio_categoria)
                            .addComponent(jRadio_descri)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_busca)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_update)
                    .addComponent(jButton_delete))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadio_categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_descri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_busca))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getListaCategorias();
        this.getListaProdutos();
    }//GEN-LAST:event_formWindowOpened

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        if(jComboBox1.getSelectedItem() != null
                && !jTextField_descricao.getText().equals("")
                && !jTextField_qtd.getText().equals("")
                && !jTextField_valor.getText().equals("")){
            
            Categoria categoria = (Categoria) jComboBox1.getSelectedItem();
            
            if(produtoController.create(jTextField_descricao.getText(), 
                                        Integer.parseInt(jTextField_qtd.getText()), 
                                        Double.parseDouble(jTextField_valor.getText()), 
                                        categoria)){
                
                JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!");
                this.getListaProdutos();
                this.limparCampos();
            
            }else{
                //Por algum motivo este laço sempre entra no else
                //mesmo que o if seja true
                //Visto isso, coloquei as funcoes aqui :D
                JOptionPane.showMessageDialog(this, "Erro ao salvar produto",
                "Erro", JOptionPane.ERROR_MESSAGE);
                this.getListaProdutos();
                this.limparCampos();
            }
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTable_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_produtosMouseClicked
        if(jTable_produtos.getSelectedRow() != -1){
            
        jTextField_descricao.setText((String) jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 1));
        jTextField_qtd.setText(String.valueOf(jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 2)));
        jTextField_valor.setText(String.valueOf(jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 3)));
        String categoria = (String) jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 4);
        
            for(int i=0;i<jComboBox1.getItemCount(); i++){
                Categoria c = (Categoria) jComboBox1.getItemAt(i);
                if(c.getDescricao().equals(categoria)){
                    jComboBox1.setSelectedIndex(i);
                }
            }
        }
    }//GEN-LAST:event_jTable_produtosMouseClicked

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        if(jTable_produtos.getSelectedRow() != -1 && jComboBox1.getSelectedItem() != null){
            Categoria categoria = (Categoria) jComboBox1.getSelectedItem();
            produtoController.update((int) jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 0), 
                    jTextField_descricao.getText(), 
                    Integer.parseInt(jTextField_qtd.getText()), 
                    Double.parseDouble(jTextField_valor.getText()), 
                    categoria);
            
            this.getListaProdutos();
            this.limparCampos();
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        if(jTable_produtos.getSelectedRow() != -1){
            produtoController.delete((int) jTable_produtos.getValueAt(jTable_produtos.getSelectedRow(), 0));
            
            this.getListaProdutos();
            this.limparCampos();
        }else{
            JOptionPane.showMessageDialog(this, "Erros ao deletar produto");
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jRadio_descriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_descriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_descriActionPerformed

    private void jButton_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscaActionPerformed
        
        DefaultTableModel modeloTableProdutos = (DefaultTableModel) jTable_produtos.getModel();
        modeloTableProdutos.setNumRows(0);
        
        ArrayList<Produto> lsProdutosBusca = new ArrayList<>();
        
        if(jRadio_descri.isSelected()){
            lsProdutosBusca = produtoController.getListaProdutosporDescricao(jTextField_busca.getText());
        }else if(jRadio_categoria.isSelected()){
            lsProdutosBusca = produtoController.getListaProdutosporCategoria(jTextField_busca.getText());
        }
        
        for (Produto p : lsProdutosBusca){
            
            modeloTableProdutos.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getValor(),
                p.getCategoria().getDescricao()
            });
        }
    }//GEN-LAST:event_jButton_buscaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mainMenu mainMenu = new mainMenu();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produtoView().setVisible(true);
            }
        });
    }
    
    public void getListaCategorias(){
        categoriaController categoriaController = new categoriaController();
        
        for(Categoria c : categoriaController.read()){
            jComboBox1.addItem(c);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_busca;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadio_categoria;
    private javax.swing.JRadioButton jRadio_descri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_produtos;
    private javax.swing.JTextField jTextField_busca;
    private javax.swing.JTextField jTextField_descricao;
    private javax.swing.JTextField jTextField_qtd;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables
}
